### KNN Imputer

In [1]:
from sklearn.impute import KNNImputer

In [35]:
df = pd.read_csv(r"\Users\Anjli Kumari\datasets\titanic.csv",usecols=['Age','Pclass','Fare','Survived'])
df.head(5)

,Survived,Pclass,Age,Fare
0,0,3,22.0,7.2500
1,1,1,38.0,71.2833
2,1,3,26.0,7.9250
3,1,1,35.0,53.1000
4,0,3,35.0,8.0500


In [37]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
dtype: float64

In [4]:
X = df.drop(columns=['Survived'])
Y = df['Survived']

In [5]:
X_train,X_test,Y_train,Y_test = train(X,Y,0.2,2)
X_train.head()

,Pclass,Age,Fare
30,1,40.0,27.7208
10,3,4.0,16.7000
873,3,47.0,9.0000
182,3,9.0,31.3875
876,3,20.0,9.8458


In [27]:
knn = KNNImputer(n_neighbors=3,weights='distance')
X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [28]:
# missing values is imputed
pd.DataFrame(X_train_trf,columns=X_train.columns)

,Pclass,Age,Fare
0,1.0,40.000000,27.7208
1,3.0,4.000000,16.7000
2,3.0,47.000000,9.0000
3,3.0,9.000000,31.3875
4,3.0,20.000000,9.8458
...,...,...,...
707,3.0,30.000000,8.6625
708,3.0,26.959410,8.7125
709,1.0,71.000000,49.5042
710,1.0,32.666667,221.7792


In [29]:
lr = LogisticRegression()
lr.fit(X_train_trf,Y_train)
Y_pred = lr.predict(X_test_trf)
accuracy_score(Y_test,Y_pred)

0.7039106145251397

In [30]:
si = imputer()
X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [31]:
lr = LogisticRegression()
lr.fit(X_train_trf2,Y_train)
Y_pred2 = lr.predict(X_test_trf2)
accuracy_score(Y_test,Y_pred2)

0.6927374301675978

### Iterative Imputer Using Pandas

In [1]:
df = np.round(pd.read_csv(r"\Users\Anjli Kumari\datasets\50_Startups.csv")[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

,R&D Spend,Administration,Marketing Spend,Profit
21,8.0,15.0,30.0,11.0
37,4.0,5.0,20.0,9.0
2,15.0,10.0,41.0,19.0
14,12.0,16.0,26.0,13.0
44,2.0,15.0,3.0,7.0


In [2]:
df = df.iloc[:,0:-1]
df

,R&D Spend,Administration,Marketing Spend
21,8.0,15.0,30.0
37,4.0,5.0,20.0
2,15.0,10.0,41.0
14,12.0,16.0,26.0
44,2.0,15.0,3.0


In [4]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

In [5]:
df.head()

,R&D Spend,Administration,Marketing Spend
21,8.0,15.0,30.0
37,NaN,5.0,20.0
2,15.0,10.0,41.0
14,12.0,NaN,26.0
44,2.0,15.0,NaN


In [51]:
X_train = df
X_test = [['NaN',5.0,50.0],[13.0,'NaN',25.0],[4.0,15.0,'NaN']]

In [8]:
df0 = pd.DataFrame()
def fill(col):
    df0[col] = df[col].fillna(df[col].mean())
fill('R&D Spend')
fill('Administration')
fill('Marketing Spend')

In [9]:
df0

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.00
37,9.25,5.00,20.00
2,15.00,10.00,41.00
14,12.00,11.25,26.00
44,2.00,15.00,29.25


In [10]:
df1 = df0.copy()
df1.iloc[1,0] = np.nan
df1

,R&D Spend,Administration,Marketing Spend
21,8.0,15.00,30.00
37,NaN,5.00,20.00
2,15.0,10.00,41.00
14,12.0,11.25,26.00
44,2.0,15.00,29.25


In [12]:
X = df1.iloc[[0,2,3,4],1:3]
Y = df1.iloc[[0,2,3,4],0]

In [16]:
lr = LinearRegression()
lr.fit(X,Y)
lr.predict(df.iloc[1,1:].values.reshape(1,2))

C:\Users\Anjli Kumari\anaconda3\envs\machine_learning\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.14158651])

In [18]:
df1.iloc[1,0] = 23.14
df1

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.00
37,23.14,5.00,20.00
2,15.00,10.00,41.00
14,12.00,11.25,26.00
44,2.00,15.00,29.25


In [19]:
df1.iloc[3,1] = np.nan
df1

,R&D Spend,Administration,Marketing Spend
21,8.00,15.0,30.00
37,23.14,5.0,20.00
2,15.00,10.0,41.00
14,12.00,NaN,26.00
44,2.00,15.0,29.25


In [20]:
X = df1.iloc[[0,1,2,4],[0,2]]
Y = df1.iloc[[0,1,2,4],1]

In [23]:
lr = LinearRegression()
lr.fit(X,Y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\Anjli Kumari\anaconda3\envs\machine_learning\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.06331285])

In [25]:
df1.iloc[3,1] = 11.06
df1

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.00
37,23.14,5.00,20.00
2,15.00,10.00,41.00
14,12.00,11.06,26.00
44,2.00,15.00,29.25


In [26]:
df1.iloc[4,-1] = np.nan
df1

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.0
37,23.14,5.00,20.0
2,15.00,10.00,41.0
14,12.00,11.06,26.0
44,2.00,15.00,NaN


In [27]:
X = df1.iloc[0:4,0:2]
Y = df1.iloc[0:4,-1]

In [30]:
lr = LinearRegression()
lr.fit(X,Y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

C:\Users\Anjli Kumari\anaconda3\envs\machine_learning\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([31.56351448])

In [32]:
df1.iloc[4,-1] = 31.56
df1

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.00
37,23.14,5.00,20.00
2,15.00,10.00,41.00
14,12.00,11.06,26.00
44,2.00,15.00,31.56


In [33]:
df1 - df0

,R&D Spend,Administration,Marketing Spend
21,0.00,0.00,0.00
37,13.89,0.00,0.00
2,0.00,0.00,0.00
14,0.00,-0.19,0.00
44,0.00,0.00,2.31


In [35]:
df2 = df1.copy()
df2.iloc[1,0] = np.nan
X1 = df1.iloc[[0,2,3,4],1:3]
Y1 = df1.iloc[[0,2,3,4],0]
lr = LinearRegression()
lr.fit(X1,Y1)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

C:\Users\Anjli Kumari\anaconda3\envs\machine_learning\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.78627207])

In [38]:
df2.iloc[1,0] = 23.78
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
Y = df2.iloc[[0,1,2,4],1]
lr = LinearRegression()
lr.fit(X,Y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\Anjli Kumari\anaconda3\envs\machine_learning\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.22020174])

In [39]:
df2.iloc[3,1] = 11.22
df2.iloc[4,-1] =np.nan
X = df2.iloc[0:4,0:2]
Y = df2.iloc[0:4,-1]
lr = LinearRegression()
lr.fit(X,Y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

C:\Users\Anjli Kumari\anaconda3\envs\machine_learning\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([38.87979054])

In [41]:
df2.iloc[4,-1] = 31.56
df2 - df1

,R&D Spend,Administration,Marketing Spend
21,0.00,0.00,0.0
37,0.64,0.00,0.0
2,0.00,0.00,0.0
14,0.00,0.16,0.0
44,0.00,0.00,0.0


In [43]:
df3 = df2.copy()
df3.iloc[1,0] = np.nan
X = df3.iloc[[0,2,3,4],1:3]
Y = df3.iloc[[0,2,3,4],0]
lr = LinearRegression()
lr.fit(X,Y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

C:\Users\Anjli Kumari\anaconda3\envs\machine_learning\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([24.57698058])

In [44]:
df3.iloc[1,0] = 24.57
df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
Y = df3.iloc[[0,1,2,4],1]
lr = LinearRegression()
lr.fit(X,Y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\Anjli Kumari\anaconda3\envs\machine_learning\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.37282844])

In [46]:
df3.iloc[3,1] = 11.37
df3.iloc[4,-1] = np.nan
X = df3.iloc[0:4,0:2]
Y = df3.iloc[0:4,-1]
lr = LinearRegression()
lr.fit(X,Y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

C:\Users\Anjli Kumari\anaconda3\envs\machine_learning\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([45.53976417])

In [48]:
df3.iloc[4,-1] = 45.53
df2.iloc[3,1] = 11.22
df3-df2

,R&D Spend,Administration,Marketing Spend
21,0.00,0.00,0.00
37,0.79,0.00,0.00
2,0.00,0.00,0.00
14,0.00,0.15,0.00
44,0.00,0.00,13.97


### Iterative Imputer Using Scikit-learn

In [3]:
df = pd.read_csv(r"\Users\Anjli Kumari\datasets\50_Startups.csv")
df.head(1)

,R&D Spend,Administration,Marketing Spend,State,Profit
0,165349.2,136897.8,471784.1,New York,192261.83


In [38]:
df['ProfitClass'] = (df['Profit'] >= df['Profit'].median()).astype(int)
df.head()

,R&D Spend,Administration,Marketing Spend,State,Profit,ProfitClass
0,165349.20,136897.80,471784.10,New York,192261.83,1
1,162597.70,151377.59,443898.53,California,191792.06,1
2,153441.51,101145.55,407934.54,Florida,191050.39,1
3,144372.41,118671.85,383199.62,New York,182901.99,1
4,142107.34,91391.77,366168.42,Florida,166187.94,1


In [40]:
X = df.iloc[:,0:3]
Y = df.iloc[:,-1]
Y

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
Name: ProfitClass, dtype: int64

In [34]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
X_train,X_test,Y_train,Y_test = train(X,Y,0.2,42)
imp = IterativeImputer(estimator=LinearRegression(),max_iter=10,random_state=42)
X_train_trf = imp.fit_transform(X_train)
X_test_trf = imp.transform(X_test)
lr = LinearRegression()
lr.fit(X_train_trf,Y_train)
Y_pred = lr.predict(X_test_trf)
print("R2 Score:",r2_score(Y_test,Y_pred))

R2 Score: 0.9000653083037321


In [45]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
X_train,X_test,Y_train,Y_test = train(X,Y,0.2,42)
imp = IterativeImputer(estimator=LinearRegression(),max_iter=13,random_state=42)
X_train_trf = imp.fit_transform(X_train)
X_test_trf = imp.transform(X_test)
lor = LogisticRegression(max_iter=1000)
lor.fit(X_train_trf,Y_train)
Y_pred = lor.predict(X_test_trf)
print("Accuracy:",accuracy_score(Y_test,Y_pred))

Accuracy: 0.7


In [46]:
for seed in [1, 10, 20, 30, 40, 42, 50, 100]:
    X_train, X_test, Y_train, Y_test = train_test_split(
        X, Y,
        test_size=0.2,
        random_state=seed,
        stratify=Y
    )

    imp = IterativeImputer(
        estimator=LinearRegression(),
        max_iter=10,
        random_state=42
    )

    X_train_trf = imp.fit_transform(X_train)
    X_test_trf = imp.transform(X_test)

    lor = LogisticRegression(max_iter=1000)
    lor.fit(X_train_trf, Y_train)

    Y_pred = lor.predict(X_test_trf)

    print(seed, accuracy_score(Y_test, Y_pred))

1 1.0
10 1.0
20 1.0
30 1.0
40 0.7
42 0.9
50 0.8
100 0.9


In [47]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[5 0]
 [1 4]]
              precision    recall  f1-score   support

           0       0.83      1.00      0.91         5
           1       1.00      0.80      0.89         5

    accuracy                           0.90        10
   macro avg       0.92      0.90      0.90        10
weighted avg       0.92      0.90      0.90        10

